// Generated by CoffeeScript 1.7.1
(function() {
  var Admin, Server;

  Server = (function() {
    function Server() {}

    Server.local = "//puzlet.mvclark.dev";

    Server["public"] = "//puzlet.mvclark.com";

    Server.isLocal = window.location.hostname === "localhost";

    Server.url = Server.isLocal ? Server.local : Server["public"];

    Server.getAll = function(callback) {
      return $.get("" + this.url, function(data) {
        this.data = data;
        console.log("All exercises from server", this.data);
        return typeof callback === "function" ? callback(this.data) : void 0;
      });
    };

    return Server;

  })();

  Admin = (function() {
    function Admin() {
      Server.getAll((function(_this) {
        return function(data) {
          _this.data = data;
          _this.model();
          console.log("SERVER");
          return _this.view();
        };
      })(this));
    }

    Admin.prototype.model = function() {
      var rec, record, _base, _i, _len, _name, _ref;
      this.report = {};
      _ref = this.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        record = _ref[_i];
        rec = (_base = this.report)[_name = record.userId] != null ? _base[_name] : _base[_name] = {};
        rec[record.exerciseId] = {
          correct: record.correct,
          code: record.code
        };
      }
      return console.log("report", this.report);
    };

    Admin.prototype.view = function() {
      var code, exercise, exerciseContainer, exerciseId, id, user, userContainer, userExercises, _ref, _results;
      this.container = $("#report");
      _ref = this.report;
      _results = [];
      for (user in _ref) {
        userExercises = _ref[user];
        userContainer = this.div("user", null, this.container);
        this.div("user-id", user, userContainer);
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (exerciseId in userExercises) {
            exercise = userExercises[exerciseId];
            console.log("user/exId/correct/code", user, exerciseId, exercise.correct, exercise.code);
            exerciseContainer = this.div("exercise", null, userContainer);
            exerciseContainer.addClass(exercise.correct ? "correct" : "incorrect");
            id = this.div("exercise-id", exerciseId);
            code = this.div("exercise-code", "<pre>" + exercise.code + "</pre>");
            _results1.push(exerciseContainer.append(id).append(code));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Admin.prototype.div = function(cls, content, container) {
      var div;
      console.log("div", cls, content, container);
      div = $("<div>", {
        "class": cls
      });
      if (content) {
        div.append(content);
      }
      console.log("C", container);
      if (container) {
        container.append(div);
      }
      return div;
    };

    Admin.prototype.append = function(element) {
      return this.container.append(element);
    };

    return Admin;

  })();

  new Admin;

}).call(this);
